# Generated by Django 2.2.4 on 2021-06-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSociety', '0002_auto_20210607_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duenos',
            old_name='correo',
            new_name='email',
        ),
    ]
